#!/usr/bin/env perl
use warnings;
use strict;
use Env qw($HOME);
use File::Slurp;

my $bookmark = `wl-paste`;
my $file = "$HOME/.local/share/bookmarks";
my @bookmarks = read_file($file);

if (! grep(/^$bookmark/, @bookmarks)) {
    open(FH, ">>", $file) or die "can't open bookmarks";
    print FH $bookmark;
    closedir
    system("notify-send 'Added bookmark!' '$bookmark'");
} else {
    system("notify-send 'Error!' 'already added'");
}
