#!/usr/bin/env perl

use warnings;
use strict;

my $conf = `echo "sway\nemacs\nwaybar\ndunst\nkitty\nstarship\nbookmarks" | bemenu -l 10 -p "Config: "`;
my $editor = "emacsclient -c";
chomp $conf;

if ($conf eq "sway") {
	`$editor ~/.config/sway/README.org`;
} elsif ($conf eq "emacs") {
    `$editor ~/.config/emacs/config.org`;    
} elsif ($conf eq "waybar") {
    `$editor ~/.config/waybar/config`;
} elsif ($conf eq "dunst") {
    `$editor ~/.config/dunst/dunstrc`;
} elsif ($conf eq "kitty") {
    `$editor ~/.config/kitty/kitty.conf`;
} elsif ($conf eq "starship") {
    `$editor ~/.config/starship.toml`;
} elsif ($conf eq "bookmarks") {
    `$editor ~/.local/share/bookmarks`;
} else {
    print "what";
}
