#!/bin/bash
# changeVolume

# Arbitrary but unique message tag
msgTag="mybrightness"

# Query amixer for the current volume and whether or not the speaker is muted
brightness=$(brightnessctl get)
# Makes it human readable
human=$(($brightness/68))

dunstify -a "changeBrightness" -u low -i display-brightness-high-symbolic -h string:x-dunst-stack-tag:$msgTag "Brightness: ${human}%"
canberra-gtk-play -i audio-volume-change -d "changeBrightness"
