import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 5 }
opacity = 0.9

[font]
normal = { family = "FiraCode Nerd Font" }
size = 12
